baseurl: "/site1" # the subpath of your site, e.g. /blog
description: "Miscellaneous nuggets of knowledge and interest."
title: "Bits of tedium"

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
gems:
  - jekyll-coffeescript
  - jekyll-paginate

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"

paginate: 5
paginate_path: "page:num/"
